### ISSUE TITLE
LIV Golf - Image conversation degridation issue

### ISSUE THREAD

**Issue by NickBertucci** [StarkRFID/Message-Broker#14]
Upon looking into printing yesterday with Evan and Will. It seems like printing the pdf file un converted seems to come out with better quality. Creating and issue here to see if we are getting image degradation during the conversion from PDF to bitmap and see if we can optimize this to create better quality images which should result in better quality prints.

**Comment by ebondur** [comment]
Wrong repo! Closing this one....
